name: Deploy to Azure App Service (Docker Hub)

on:
  push:
    branches: [ main, develop ]
    paths:
      - "pages/**"
      - "components/**"
      - "services/**"
      - "styles/**"
      - "package.json"
      - "Dockerfile"
      - ".github/workflows/azure-deploy.yml"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: rlfrkdms1/front-end-services  # Docker Hub 리포지토리명으로 변경 필요
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (Docker Hub)
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
          docker tag $IMAGE_NAME:${{ steps.vars.outputs.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          docker push $IMAGE_NAME:latest

      # Azure Web App에 Docker 이미지 배포
      - name: Deploy to Azure Web App (container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: index.docker.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

      # 환경변수 설정
      - name: Set environment variables
        run: |
          echo "환경변수 설정 중..."
          # Azure CLI를 통해 환경변수 설정 (선택사항)
          # az webapp config appsettings set \
          #   --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          #   --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          #   --settings NODE_ENV=production PORT=3000

      # 배포 완료 후 대기
      - name: Wait for deployment
        run: |
          echo "배포 완료 후 헬스체크 대기 중..."
          sleep 60

      # 헬스체크 (선택사항)
      - name: Health check
        run: |
          echo "애플리케이션 헬스체크 중..."
          # Azure Web App URL로 헬스체크 (URL을 secrets에 추가 필요)
          # curl -f ${{ secrets.AZURE_WEBAPP_URL }}/api/health || echo "헬스체크 실패"
